import React, { useState } from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import { H1 } from '../components/Typography'
import {
  XYPlot,
  LineSeries,
  VerticalGridLines,
  HorizontalGridLines,
  XAxis,
  YAxis,
  VerticalBarSeries,
} from 'react-vis'
import '../node_modules/react-vis/dist/style.css'

const Home: NextPage = () => {
  //Karlshamn

  const data = [
    { x: 1990, y: 244858 },
    { x: 2000, y: 269628 },
    { x: 2005, y: 286327 },
    { x: 2010, y: 329532 },
    { x: 2011, y: 202260 },
    { x: 2012, y: 197892 },
    { x: 2013, y: 172924 },
    { x: 2014, y: 138393 },
    { x: 2015, y: 142491 },
    { x: 2016, y: 139340 },
    { x: 2017, y: 125147 },
    { x: 2018, y: 146469 },
    { x: 2019, y: 115844 },
  ]

  // const data = [
  //   { x: 1990, y: 4 },
  //   { x: 2000, y: 7 },
  //   { x: 2005, y: 3 },
  //   { x: 2010, y: 8 },
  // ]

  // const [data, setData] = useState<any>(data)

  // setTimeout(() => {
  //   const newItem = [...data, { x: 2015, y: 2 }]

  //   setData(newItem)

  //   console.log(newItem)
  // }, 5000)

  return (
    <div>
      <Head>
        <title>Klimatkollen</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div style={{ margin: '10px', backgroundColor: 'lightblue' }}>
        <XYPlot
          xType="ordinal"
          yType="linear"
          height={500}
          width={500}
          // animation={{ damping: 9, stiffness: 300 }}
        >
          {/* <VerticalGridLines />
        <HorizontalGridLines /> */}
          <XAxis left={40} title="Year" />
          <YAxis left={17} title="co2" />
          <LineSeries data={data} />

          {/* <LineSeries data={DATA[1]} /> */}
          {/* <LineSeries data={data} /> */}
          {/* <VerticalBarSeries data={data} /> */}
        </XYPlot>
      </div>
    </div>
  )
}

export default Home
